### ISSUE TITLE
서버 스크립트 사용법좀요..

### ISSUE THREAD

**Issue by xenon245** [monun/server-script#1]
서버 스크립트 어떻게 사용하는 건가요?
어떤 터미널로 열어야 하는지 어떤 명령어로 실행해야 하는지 알려주세요

**Comment by ghost** [comment]
google it.

...농담이고 리눅스쪽에서 `chmod +x 스크립트파일`하고
`./스크립트 파일` 하면 아마 동작할겁니다.

(어... 리눅스 버전마다 달라서 그런건지 모르겠는데 저는 작동이 안되더라고요 다른 리눅스 에디션 확인해보고 이슈달까 생각중입니다)
