### ISSUE TITLE
[m?[K 같은 이상한 문자가 나옵니다.

### ISSUE THREAD

**Issue by chlee7139** [monun/server-script#10]
inteliJ에 Git bash를 연동하여 사용중인데
?[K[08:40:28 INFO]: [AutoReloader] Enabling AutoReloader v0.0.2?[m
?[K[08:40:28 INFO]: Running delayed init tasks?[m
?[K[08:40:28 INFO]: [AutoReloader] - AutoReloader: plugins\update\AutoReloader.jar?[m
?[K[08:40:28 INFO]: Done (1.960s)! For help, type "help"?[m
?[K[08:40:28 INFO]: Timings Reset?[m
이렇게 이상한 문자열이 따라나옵니다. stop을 입력하면
?[31ms?[0m?[31mt?[0m?[31mo?stop?[K
이게 뜹니다. 뭐가 문제일까요

**Comment by monun** [comment]
전 이렇게 사용하고있어요

![image](https://user-images.githubusercontent.com/77531416/132243310-dcc831c8-5020-4402-be1f-4d8e4a66d52c.png)
